---
title: "Master thesis data table"
author: "Elena-Madalina Hizanu"
date: "2023-02-02"
output: html_document
---
```{r libraries}

library(tidyverse)
library(ggplot2)
library(dplyr)
library(readxl)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load data from the main table

```{r main table import}

Gluten_samlet_datasæt_med_CSV <- read_excel("Gluten samlet datasæt med CSV.xlsx", sheet = 'Debut')

```

## filter and clean the first sheet

```{r data cleaning and filtering 1st sheet}

df1_selcted <- Gluten_samlet_datasæt_med_CSV %>%
  select(`pt-ID`:`Vitamin D måling`, -'J-nr FU', -'ON debut dato', -'dato for MS diagnose', -`MR gluten t0`, -`Første MR`, -`MS-relevant Historik`, -`Lumbalpunktur dato`, -`Vitamin D dato`)
  

#selecting only the intervention and control patients

df1_filtered_pt_woexp <- df1_selcted %>%
  filter(Flowdiagram %in% c('Intervention', 'Control'))

#changing NA's in all diagnosis columns

df1_filtered_pt_woexp_NAchange <- df1_filtered_pt_woexp %>%
  mutate(`Diagnose ved debut` = ifelse(is.na(`Diagnose ved debut`), 
                                       'NMS', 
                                       'MS')) %>%
  
  mutate(`Diagnose ved 6mr FU` = ifelse(is.na(`Diagnose ved 6mr FU`) &
                                          `Diagnose ved debut` == 'NMS',
                                        'NMS',
                                        'MS')) %>%
  
  mutate(`Diagnose i Nov 2022` = ifelse(is.na(`Diagnose i Nov 2022`) &
                                          `Diagnose ved 6mr FU`== 'NMS',
                                        'NMS',
                                        'MS'))
        
```

##filter and clean second sheet

```{r data cleaning and filtering 2nd sheet}



```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
